version: "3.9"

services:
  postgres:
    container_name: postgres-db
    image: postgres:17.1-alpine3.20
    env_file: .env
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"